import 'package:flutter/material.dart';

abstract final class AppColorsLight {
  static const ColorScheme scheme = ColorScheme(
    brightness               : Brightness.light,
    primary                  : Color(0xFF785C99),
    onPrimary                : Color(0xFFFFFFFF),
    primaryContainer         : Color(0xFFEEDBFF),
    onPrimaryContainer       : Color(0xFF270D43),
    primaryFixed             : Color(0xFFEEDBFF),
    primaryFixedDim          : Color(0xFFD9BAFA),
    onPrimaryFixed           : Color(0xFF270D43),
    onPrimaryFixedVariant    : Color(0xFF543B72),
    secondary                : Color(0xFF6D71B4),
    onSecondary              : Color(0xFFFFFFFF),
    secondaryContainer       : Color(0xFFE1DDFF),
    onSecondaryContainer     : Color(0xFF0F0F10),
    secondaryFixed           : Color(0xFFE1E0F9),
    secondaryFixedDim        : Color(0xFFC5C4DD),
    onSecondaryFixed         : Color(0xFF191A2C),
    onSecondaryFixedVariant  : Color(0xFF444559),
    tertiary                 : Color(0xFF6A5EA0),
    onTertiary               : Color(0xFFFFFFFF),
    tertiaryContainer        : Color(0xFFE6DEFF),
    onTertiaryContainer      : Color(0xFF1D1736),
    tertiaryFixed            : Color(0xFFE6DEFF),
    tertiaryFixedDim         : Color(0xFFCAC1E9),
    onTertiaryFixed          : Color(0xFF1D1736),
    onTertiaryFixedVariant   : Color(0xFF484264),
    error                    : Color(0xFFB62320),
    onError                  : Color(0xFFFFFFFF),
    errorContainer           : Color(0xFFFFDAD6),
    onErrorContainer         : Color(0xFF410002),
    surface                  : Color(0xFFFFFFFF),
    onSurface                : Color(0xFF1D1A20),
    surfaceDim               : Color(0xFFEBE6EB),
    surfaceBright            : Color(0xFFFFFFFF),
    surfaceContainerLowest   : Color(0xFFE2E2E2),
    surfaceContainerLow      : Color(0xFFFFFFFF),
    surfaceContainer         : Color(0xFFFDFBFD),
    surfaceContainerHigh     : Color(0xFFF8F5F8),
    surfaceContainerHighest  : Color(0xFFF3EFF3),
    onSurfaceVariant         : Color(0xFF4A454E),
    outline                  : Color(0xFF7B757F),
    outlineVariant           : Color(0xFFCCC4CF),
    shadow                   : Color(0xFF000000),
    scrim                    : Color(0xFF000000),
    inverseSurface           : Color(0xFF262327),
    onInverseSurface         : Color(0xFFFFFFFF),
    inversePrimary           : Color(0xFFD9BAFA),
    surfaceTint              : Color(0xFF6D538B),
  );
}

abstract final class AppColorsDark {
  static const ColorScheme scheme = ColorScheme(
    brightness               : Brightness.dark,
    primary                  : Color(0xFFEEDBFF),
    onPrimary                : Color(0xFF000000),
    primaryContainer         : Color(0xFF785C99),
    onPrimaryContainer       : Color(0xFFF9F7FB),
    primaryFixed             : Color(0xFFEEDBFF),
    primaryFixedDim          : Color(0xFFD8BAFA),
    onPrimaryFixed           : Color(0xFF270D43),
    onPrimaryFixedVariant    : Color(0xFF543B72),
    secondary                : Color(0xFFE1DDFF),
    onSecondary              : Color(0xFF000000),
    secondaryContainer       : Color(0xFF6D71B4),
    onSecondaryContainer     : Color(0xFFF8F8FE),
    secondaryFixed           : Color(0xFFE3E0F9),
    secondaryFixedDim        : Color(0xFFC7C4DC),
    onSecondaryFixed         : Color(0xFF1B1A2C),
    onSecondaryFixedVariant  : Color(0xFF464559),
    tertiary                 : Color(0xFFCBBEFF),
    onTertiary               : Color(0xFF000000),
    tertiaryContainer        : Color(0xFF615597),
    onTertiaryContainer      : Color(0xFFF7F6FB),
    tertiaryFixed            : Color(0xFFE6DEFF),
    tertiaryFixedDim         : Color(0xFFCAC1E9),
    onTertiaryFixed          : Color(0xFF1D1736),
    onTertiaryFixedVariant   : Color(0xFF494264),
    error                    : Color(0xFFC84750),
    onError                  : Color(0xFFFFFFFF),
    errorContainer           : Color(0xFF93000A),
    onErrorContainer         : Color(0xFFFBEFF0),
    surface                  : Color(0xFF161319),
    onSurface                : Color(0xFFE8E0E8),
    surfaceDim               : Color(0xFF161319),
    surfaceBright            : Color(0xFF3D393F),
    surfaceContainerLowest   : Color(0xFF110E13),
    surfaceContainerLow      : Color(0xFF1E1B21),
    surfaceContainer         : Color(0xFF231F25),
    surfaceContainerHigh     : Color(0xFF2D2A30),
    surfaceContainerHighest  : Color(0xFF38343A),
    onSurfaceVariant         : Color(0xFFCCC4CF),
    outline                  : Color(0xFF958E98),
    outlineVariant           : Color(0xFF4A454E),
    shadow                   : Color(0xFF000000),
    scrim                    : Color(0xFF000000),
    inverseSurface           : Color(0xFFE8E0E8),
    onInverseSurface         : Color(0xFF332F35),
    inversePrimary           : Color(0xFF6C538B),
    surfaceTint              : Color(0xFFD8BAFA),
  );
}